name: Firebase Deployment

on:
  pull_request:  # For preview deployments
  push:
    branches:
      - main     # For production deployments

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Create environment config
      - name: Create environment config
        run: |
          echo "const ENV = {" > public/config/env-config.js
          echo "  FIREBASE_API_KEY: \"${{ secrets.FIREBASE_API_KEY }}\"," >> public/config/env-config.js
          echo "  FIREBASE_AUTH_DOMAIN: \"${{ secrets.FIREBASE_AUTH_DOMAIN }}\"," >> public/config/env-config.js
          echo "  FIREBASE_PROJECT_ID: \"${{ secrets.FIREBASE_PROJECT_ID }}\"," >> public/config/env-config.js
          echo "  FIREBASE_STORAGE_BUCKET: \"${{ secrets.FIREBASE_STORAGE_BUCKET }}\"," >> public/config/env-config.js
          echo "  FIREBASE_MESSAGING_SENDER_ID: \"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}\"," >> public/config/env-config.js
          echo "  FIREBASE_APP_ID: \"${{ secrets.FIREBASE_APP_ID }}\"," >> public/config/env-config.js
          echo "  FIREBASE_MEASUREMENT_ID: \"${{ secrets.FIREBASE_MEASUREMENT_ID }}\"" >> public/config/env-config.js
          echo "};" >> public/config/env-config.js
          echo "export default ENV;" >> public/config/env-config.js

      # Install dependencies for root project and functions
      - name: Install Dependencies
        run: |
          npm ci
          cd functions && npm ci

      # For Pull Requests - Only deploy Hosting preview
      - name: Deploy Hosting Preview (PR only)
        if: github.event_name == 'pull_request'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: thetataumiamiuniversity
          channelId: preview

      # For main branch - Deploy both Hosting and Functions
      - name: Deploy Production (main branch only)
        if: github.ref == 'refs/heads/main'
        run: |
          npm install -g firebase-tools
          python3.12 -m venv functions/venv
          source functions/venv/bin/activate
          pip install -r functions/requirements.txt
          firebase deploy --only hosting,functions --token "${{ secrets.FIREBASE_TOKEN }}" --project thetataumiamiuniversity