name: Deploy to Firebase Hosting on PR

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Allows reading repo contents
      checks: write   # ✅ Allows Firebase to create check runs
      pull-requests: write  # ✅ Allows Firebase to comment on PRs (optional)

    steps:
      - uses: actions/checkout@v3

      - name: Create environment config
        run: |
          echo "const ENV = {" > public/config/env-config.js
          echo "  FIREBASE_API_KEY: \"${{ secrets.FIREBASE_API_KEY }}\"," >> public/config/env-config.js
          echo "  FIREBASE_AUTH_DOMAIN: \"${{ secrets.FIREBASE_AUTH_DOMAIN }}\"," >> public/config/env-config.js
          echo "  FIREBASE_PROJECT_ID: \"${{ secrets.FIREBASE_PROJECT_ID }}\"," >> public/config/env-config.js
          echo "  FIREBASE_STORAGE_BUCKET: \"${{ secrets.FIREBASE_STORAGE_BUCKET }}\"," >> public/config/env-config.js
          echo "  FIREBASE_MESSAGING_SENDER_ID: \"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}\"," >> public/config/env-config.js
          echo "  FIREBASE_APP_ID: \"${{ secrets.FIREBASE_APP_ID }}\"," >> public/config/env-config.js
          echo "  FIREBASE_MEASUREMENT_ID: \"${{ secrets.FIREBASE_MEASUREMENT_ID }}\"" >> public/config/env-config.js
          echo "};" >> public/config/env-config.js
          echo "export default ENV;" >> public/config/env-config.js

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: thetataumiamiuniversity