name: Deploy to Firebase Hosting on PR

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Allows reading repo contents
      checks: write   # ✅ Allows Firebase to create check runs
      pull-requests: write  # ✅ Allows Firebase to comment on PRs (optional)

    steps:
      - uses: actions/checkout@v3

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: thetataumiamiuniversity