name: Deploy to Firebase Hosting and Functions

on:
  pull_request:  # For preview deployments
  push:
    branches:
      - main     # For production deployments

jobs:
  deploy_preview:
    name: Deploy Preview
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      # Create environment config
      - name: Create environment config
        run: |
          echo "const ENV = {" > public/config/env-config.js
          echo "  FIREBASE_API_KEY: \"${{ secrets.FIREBASE_API_KEY }}\"," >> public/config/env-config.js
          echo "  FIREBASE_AUTH_DOMAIN: \"${{ secrets.FIREBASE_AUTH_DOMAIN }}\"," >> public/config/env-config.js
          echo "  FIREBASE_PROJECT_ID: \"${{ secrets.FIREBASE_PROJECT_ID }}\"," >> public/config/env-config.js
          echo "  FIREBASE_STORAGE_BUCKET: \"${{ secrets.FIREBASE_STORAGE_BUCKET }}\"," >> public/config/env-config.js
          echo "  FIREBASE_MESSAGING_SENDER_ID: \"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}\"," >> public/config/env-config.js
          echo "  FIREBASE_APP_ID: \"${{ secrets.FIREBASE_APP_ID }}\"," >> public/config/env-config.js
          echo "  FIREBASE_MEASUREMENT_ID: \"${{ secrets.FIREBASE_MEASUREMENT_ID }}\"" >> public/config/env-config.js
          echo "};" >> public/config/env-config.js
          echo "export default ENV;" >> public/config/env-config.js

      # For Pull Requests - Only deploy Hosting preview
      - name: Deploy Hosting Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: thetataumiamiuniversity
          channelId: preview

  deploy_production:
    name: Deploy to Firebase
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      # Setup Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Create environment config
      - name: Create environment config
        run: |
          echo "const ENV = {" > public/config/env-config.js
          echo "  FIREBASE_API_KEY: \"${{ secrets.FIREBASE_API_KEY }}\"," >> public/config/env-config.js
          echo "  FIREBASE_AUTH_DOMAIN: \"${{ secrets.FIREBASE_AUTH_DOMAIN }}\"," >> public/config/env-config.js
          echo "  FIREBASE_PROJECT_ID: \"${{ secrets.FIREBASE_PROJECT_ID }}\"," >> public/config/env-config.js
          echo "  FIREBASE_STORAGE_BUCKET: \"${{ secrets.FIREBASE_STORAGE_BUCKET }}\"," >> public/config/env-config.js
          echo "  FIREBASE_MESSAGING_SENDER_ID: \"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}\"," >> public/config/env-config.js
          echo "  FIREBASE_APP_ID: \"${{ secrets.FIREBASE_APP_ID }}\"," >> public/config/env-config.js
          echo "  FIREBASE_MEASUREMENT_ID: \"${{ secrets.FIREBASE_MEASUREMENT_ID }}\"" >> public/config/env-config.js
          echo "};" >> public/config/env-config.js
          echo "export default ENV;" >> public/config/env-config.js

      # Create service account key file for Python functions
      - name: Create service account key file
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > functions/service-account.json

      # Modify Python code to initialize Firebase with the service account
      - name: Update Firebase initialization
        run: |
          # Check if the file has import firebase_admin at the top
          if grep -q "import firebase_admin" functions/main.py; then
            # Ensure proper initialization with service account
            if ! grep -q "firebase_admin.initialize_app" functions/main.py; then
              # Add initialization after imports
              sed -i '/import firebase_admin/a from firebase_admin import credentials\nfirebase_admin.initialize_app(credentials.Certificate("service-account.json"))' functions/main.py
            elif ! grep -q "credentials.Certificate" functions/main.py; then
              # Replace existing initialization
              sed -i 's/firebase_admin.initialize_app()/firebase_admin.initialize_app(credentials.Certificate("service-account.json"))/g' functions/main.py
            fi
          fi

      # Setup Python virtual environment
      - name: Setup Python venv and dependencies
        run: |
          cd functions
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Set up Google Cloud credentials
      - name: Set up Google Cloud credentials
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV

      # Deploy using Firebase CLI
      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --project thetataumiamiuniversity --only hosting,functions